/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shirt(props) {
  const { nodes, materials } = useGLTF('/camisa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Manga_der.geometry}
        material={materials['Material.001']}
        position={[0.097, 0.129, -0.436]}
        rotation={[2.513, 1.554, 2.246]}
        scale={[0.505, 0.31, 0.677]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Espalda.geometry}
        material={materials['Material.001']}
        position={[0.095, 0.112, -0.42]}
        rotation={[2.513, 1.554, 2.246]}
        scale={[0.505, 0.318, 0.677]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frente.geometry}
        material={materials['Material.001']}
        position={[0.095, 0.114, -0.42]}
        rotation={[2.513, 1.554, 2.246]}
        scale={[0.505, 0.318, 0.677]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cuello.geometry}
        material={materials['Material.001']}
        position={[0.075, -0.166, 0.156]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.059, 0.052, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Manga_izq.geometry}
        material={materials['Material.001']}
        position={[0.097, 0.108, -0.436]}
        rotation={[2.513, 1.554, 2.246]}
        scale={[0.505, 0.31, 0.677]}
      />
    </group>
  )
}

useGLTF.preload('/camisa.glb')
