/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function House (props) {
  const { nodes, materials } = useGLTF('/mdvr.glb')
  return (
    <group {...props} dispose={null} scale={.2}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window9Cube2.geometry}
        material={materials.Marble}
        position={[-16.6246, 8.364, -0.4661]}
        scale={[0.0962, 2.3398, 2.1767]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window5Cube3.geometry}
        material={materials.Darkglass}
        position={[-13.2926, 2.7057, 3.4908]}
        scale={[0.0962, 0.6612, 2.114]}
      />
      <group
        position={[-1.3105, 6.648, 2.5249]}
        rotation={[Math.PI, -0.0073, 0]}
        scale={[-0.0962, -0.6207, -0.854]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079.geometry}
          material={nodes.Cube079.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_1.geometry}
          material={nodes.Cube079_1.material}
        />
      </group>
      <group
        position={[-1.3105, 6.648, 2.5249]}
        rotation={[Math.PI, -0.0073, 0]}
        scale={[-0.0962, -0.6207, -0.854]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_1.geometry}
          material={materials.glow}
        />
      </group>
      <group
        position={[-8.1144, 3.8215, 5.6347]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.0743, 1.8155, 5.2925]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043.geometry}
          material={materials.Marble}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_1.geometry}
          material={materials.Popart}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window2Cube2_collider.geometry}
        material={nodes.Window2Cube2_collider.material}
        position={[-7.3046, 6.6471, 3.2663]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.0991, 0.6144, 5.9569]}
      />
      <group
        position={[-7.3046, 6.6471, 3.275]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1, 0.62, 6.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window1Cube3.geometry}
        material={materials['Glass  Invisible']}
        position={[-2.9301, 3.796, 3.5174]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.0962, 1.8155, 2.1544]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window1Cube2_collider.geometry}
        material={nodes.window1Cube2_collider.material}
        position={[-1.2077, 8.2979, -0.4641]}
        scale={[0.0962, 2.3185, 2.1767]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window1Cube2.geometry}
        material={materials.Darkglass}
        position={[-1.196, 8.2979, -0.4641]}
        scale={[0.1443, 2.3185, 2.1767]}
      />
      <group
        position={[-1.8493, 15.3498, 4.3566]}
        rotation={[Math.PI, -0.0073, Math.PI]}
        scale={[0.0914, 2.5439, 2.136]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube076.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube076_1.geometry}
          material={materials.Darkglass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window1Cube1.geometry}
        material={materials.Darkglass}
        position={[-1.8493, 15.3498, 4.3566]}
        rotation={[Math.PI, -0.0073, Math.PI]}
        scale={[0.0914, 2.5439, 2.136]}
      />
      <group
        position={[-7.9884, 8.0745, -0.7805]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.3888, 2, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={nodes.Cube056.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_1.geometry}
          material={nodes.Cube056_1.material}
        />
      </group>
      <group
        position={[-7.9884, 8.0745, -0.7805]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.3888, 2, 0.15]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials.Laocoon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials.Lacoon2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallBanksy_collider.geometry}
        material={nodes.WallBanksy_collider.material}
        position={[-4.9713, 15.3845, 2.2599]}
        scale={[3.127, 2.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallBanksy.geometry}
        material={materials.Banksy}
        position={[-4.9713, 15.3845, 2.2599]}
        scale={[3.127, 2.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall9CUbe2_collider.geometry}
        material={nodes.Wall9CUbe2_collider.material}
        position={[-14.9134, 8.3051, 3.287]}
        scale={[1.6798, 2.2931, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall9CUbe2.geometry}
        material={materials.Marble}
        position={[-14.9134, 8.3051, 3.287]}
        scale={[1.6798, 2.2931, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall9cube1_collider.geometry}
        material={nodes.Wall9cube1_collider.material}
        position={[-12.3717, 14.1319, 0.6937]}
        scale={[4.3215, 1.3344, 0.1]}
      />
      <group position={[-12.3717, 14.1319, 0.6937]} scale={[4.3215, 1.3344, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.Darkglass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall8Cube1_collider.geometry}
        material={nodes.Wall8Cube1_collider.material}
        position={[-8.1424, 14.1877, 1.3886]}
        scale={[0.0962, 1.3793, 0.8026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall8Cube1.geometry}
        material={materials['Glass  Invisible']}
        position={[-8.1424, 14.1877, 1.3886]}
        scale={[0.0962, 1.3793, 0.8026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall7Cube1_collider.geometry}
        material={nodes.Wall7Cube1_collider.material}
        position={[-13.2815, 14.1319, 6.5727]}
        scale={[3.3631, 1.3344, 0.1]}
      />
      <group position={[-13.2815, 14.1319, 6.5899]} scale={[3.3631, 1.3344, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.Darkglass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall6LC.geometry}
        material={materials.Marble}
        position={[-13.2029, 6.6779, 4.566]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.0962, -0.5894, -1.1642]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall6Cube2_collider.geometry}
        material={nodes.Wall6Cube2_collider.material}
        position={[-13.2133, 8.2901, 1.2915]}
        scale={[0.0962, 2.2186, 2.0946]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall6Cube2.geometry}
        material={materials.Marble}
        position={[-13.2133, 8.2901, 1.2915]}
        scale={[0.0962, 2.2186, 2.0946]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall6Cube1_collider.geometry}
        material={nodes.Wall6Cube1_collider.material}
        position={[-13.712, 14.2009, 4.7629]}
        rotation={[-Math.PI, 1.5635, 0]}
        scale={[-1.9, -1.3805, -0.0962]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall6Cube1.geometry}
        material={materials.Marble}
        position={[-13.712, 14.1924, 4.7629]}
        rotation={[-Math.PI, 1.5635, 0]}
        scale={[-1.9, -1.3379, -0.0962]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall5Cube1_collider.geometry}
        material={nodes.Wall5Cube1_collider.material}
        position={[-16.6346, 14.1115, 3.6823]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-3.0209, -1.3711, -0.0962]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall5Cube1.geometry}
        material={materials.Marble}
        position={[-16.6346, 14.1115, 3.6823]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-3.0209, -1.3711, -0.0962]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall4LC_collider.geometry}
        material={nodes.Wall4LC_collider.material}
        position={[-14.8654, 5.2578, 5.6267]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.659, -2.0084, -0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall4LC.geometry}
        material={materials.Marble}
        position={[-14.8654, 5.2578, 5.6267]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.659, -2.0084, -0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall3LC.geometry}
        material={materials.Marble}
        position={[-13.2782, 4.6844, 2.7]}
        scale={[0.0912, 1.4153, 1.4029]}
      />
      <group
        position={[-14.8654, 4.2016, 1.3769]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.6497, -1.0213, -0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_1.geometry}
          material={materials.Marble}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall1Cube1_collider.geometry}
        material={nodes.Wall1Cube1_collider.material}
        position={[-5.6638, 14.8739, 6.5558]}
        scale={[4.3303, 2.1048, 0.1]}
      />
      <group position={[-5.6638, 14.8907, 6.5558]} scale={[4.3303, 2.1048, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Marble}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch001.geometry}
        material={materials.Darkglass}
        position={[-13.4356, 4.6963, 3.2791]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.5, 0.8414, 0.1925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch.geometry}
        material={materials.Marble}
        position={[-3.7429, 7.3981, -0.5859]}
        rotation={[Math.PI, -0.0073, Math.PI]}
        scale={[0.4811, 0.8414, 0.1123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stairs_collider.geometry}
        material={nodes.Stairs_collider.material}
        position={[-6.1692, 14.2704, 5.462]}
        rotation={[0, 0, -0.6109]}
        scale={[2.4371, 0.9878, 0.8889]}
      />
      <group
        position={[-4.9652, 13.1302, 5.5406]}
        rotation={[Math.PI, -0.0108, Math.PI]}
        scale={[0.1443, 0.1146, 0.8889]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.Marble}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s002.geometry}
        material={materials.Marble}
        position={[-11.6691, 7.2494, 1.077]}
        rotation={[0, -0.5637, 0.0716]}
        scale={[0.1071, 0.06, 0.0594]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s001.geometry}
        material={materials.Marble}
        position={[-9.3729, 7.2494, 1.077]}
        rotation={[0, -0.5637, 0.0716]}
        scale={[0.1071, 0.06, 0.0594]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.S.geometry}
        material={nodes.S.material}
        position={[-9.3729, 7.2494, 1.077]}
        rotation={[0, -0.5637, 0.0716]}
        scale={[0.1071, 0.06, 0.0594]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s.geometry}
        material={nodes.s.material}
        position={[-11.6691, 7.2494, 1.077]}
        rotation={[0, -0.5637, 0.0716]}
        scale={[0.1071, 0.06, 0.0594]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofLC_collider.geometry}
        material={nodes.RoofLC_collider.material}
        position={[-14.8849, 7.1692, 4.5152]}
        scale={[1.6758, 0.1, 1.2064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofLC.geometry}
        material={materials.Marble}
        position={[-14.8849, 7.1692, 4.5152]}
        scale={[1.6758, 0.1, 1.2064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofCube3_collider.geometry}
        material={nodes.RoofCube3_collider.material}
        position={[-8.0043, 5.6131, 3.5128]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.1597, 0.0605, 2.1365]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofCube3.geometry}
        material={materials.Marble}
        position={[-8.0043, 5.6131, 3.5128]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.1597, 0.0605, 2.1365]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofCube2.geometry}
        material={materials.Marble}
        position={[-9.0393, 10.53, 0.3654]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.1, 7.652, 2.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofCube1_collider.geometry}
        material={nodes.RoofCube1_collider.material}
        position={[-5.6737, 17.8668, 3.05]}
        scale={[4.3303, 0.1, 2.5]}
      />
      <group position={[-5.6737, 17.8668, 3.05]} scale={[4.3303, 0.1, 2.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066_1.geometry}
          material={materials.glow}
        />
      </group>
      <group position={[-13.334, 16.2206, 6.5501]} scale={[3.3377, 0.7744, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={nodes.Cube028.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={nodes.Cube028_1.material}
        />
      </group>
      <group position={[-13.334, 16.2206, 6.5501]} scale={[3.3377, 0.7744, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials.glow}
        />
      </group>
      <group
        position={[-8.1413, 16.2279, 2.5357]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.9275, 0.7671, 0.0481]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069.geometry}
          material={nodes.Cube069.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_1.geometry}
          material={nodes.Cube069_1.material}
        />
      </group>
      <group
        position={[-8.1413, 16.2279, 2.5357]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.9275, 0.7671, 0.0481]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.glow}
        />
      </group>
      <group
        position={[-16.6957, 16.2295, 3.6261]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.0261, 0.7671, 0.0481]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube074.geometry}
          material={nodes.Cube074.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube074_1.geometry}
          material={nodes.Cube074_1.material}
        />
      </group>
      <group
        position={[-16.6957, 16.2295, 3.6261]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.0261, 0.7671, 0.0481]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials.glow}
        />
      </group>
      <group position={[-8.0878, 2.623, 1.3399]} scale={[5.1506, 0.7467, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={materials['Glass  Invisible']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={materials['Glass  Invisible']}
        />
      </group>
      <group position={[-12.3943, 16.2206, 0.6476]} scale={[4.305, 0.7744, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube072.geometry}
          material={nodes.Cube072.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube072_1.geometry}
          material={nodes.Cube072_1.material}
        />
      </group>
      <group position={[-12.3943, 16.2206, 0.6476]} scale={[4.305, 0.7744, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_1.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MAinwindowCube2.geometry}
        material={materials['Glass  Invisible']}
        position={[-8.993, 8.3196, -2.5356]}
        scale={[7.6659, 1.6078, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light6c3.geometry}
        material={materials.glow}
        position={[-8.1182, 1.9789, 5.7099]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.0814, 0.1491, 5.3056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light5c3.geometry}
        material={materials.glow}
        position={[-8.0913, 1.9789, 1.3466]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.0812, 0.1506, 5.2856]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light4c3.geometry}
        material={materials.glow}
        position={[-13.3331, 1.9734, 3.5]}
        scale={[-0.0779, -0.1491, -2.2387]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light1c3.geometry}
        material={materials.glow}
        position={[-2.8898, 1.9789, 3.5204]}
        scale={[-0.0853, -0.1547, -2.2597]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={materials.Bake}
        position={[-8.9196, 0.039, -2.9461]}
        scale={[8, 0.0914, 5.6579]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCube1_collider.geometry}
        material={nodes.FloorCube1_collider.material}
        position={[-9.031, 12.792, 3.6569]}
        scale={[7.6983, 0.1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCube1.geometry}
        material={materials.Bake}
        position={[-9.031, 12.792, 3.6569]}
        scale={[7.6983, 0.1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCL_collider.geometry}
        material={nodes.FloorCL_collider.material}
        position={[-14.9158, 3.2805, 3.5314]}
        scale={[1.6383, 0.1, 2.1624]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCL.geometry}
        material={materials.glow}
        position={[-14.9158, 3.2539, 3.5314]}
        scale={[1.6383, 0.1, 2.1624]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor2Cube2_collider.geometry}
        material={nodes.Floor2Cube2_collider.material}
        position={[-14.8645, 6.1206, -0.6579]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.6943, -0.1, -1.0951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor2Cube2.geometry}
        material={materials.wood}
        position={[-14.8645, 6.1206, -0.6579]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.6943, -0.1, -1.0951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor1Cube3_collider.geometry}
        material={materials.wood}
        position={[-8.1688, 2.0384, 3.5128]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.1558, 0.0598, 2.1485]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor1Cube3.geometry}
        material={materials.wood}
        position={[-8.1688, 1.9601, 3.5128]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.2211, 0.0605, 2.1365]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor1Cube2_collider.geometry}
        material={nodes.Floor1Cube2_collider.material}
        position={[-7.2915, 6.1079, 0.8203]}
        scale={[5.9004, 0.0841, 2.5148]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor1Cube2.geometry}
        material={materials.wood}
        position={[-7.2915, 6.1384, 0.8203]}
        scale={[5.9004, 0.1, 2.5148]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DetailLC.geometry}
        material={materials.Marble}
        position={[-16.6101, 5.0338, -0.0745]}
        scale={[0.0962, 1, 1.3805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Detailcube2.geometry}
        material={materials.Marble}
        position={[-14.9066, 10.525, 3.0327]}
        scale={[1.7822, 0.1, 0.3487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Detail2LC.geometry}
        material={materials.Marble}
        position={[-13.2833, 4.637, -0.6563]}
        scale={[0.0962, 1.4545, 1.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Deck_collider.geometry}
        material={nodes.Deck_collider.material}
        position={[-12.3997, 15.5548, 3.6094]}
        scale={[4.3303, 0.1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Deck.geometry}
        material={materials.wood}
        position={[-12.3997, 15.5548, 3.6094]}
        scale={[4.3303, 0.1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder1cube2_collider.geometry}
        material={nodes.Cylinder1cube2_collider.material}
        position={[-8.9582, 6.7474, -1.8201]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.7493, 7.731, 0.789]}
      />
      <group
        position={[-8.9582, 6.7474, -1.8201]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.7493, 7.6101, 0.789]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_3.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Marble}
        position={[-9.3697, 7.1428, 1.0848]}
        scale={[0.0386, 0.1301, 0.0401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Marble}
        position={[-9.5526, 7.2274, 0.9656]}
        rotation={[0.0529, -0.5352, 1.6743]}
        scale={[0.02, 0.2238, 0.0199]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Darkglass}
        position={[-9.719, 7.1868, 0.8609]}
        scale={[0.0039, 0.025, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Marble}
        position={[-11.6659, 7.1428, 1.0848]}
        scale={[0.0386, 0.1301, 0.0401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[-11.6659, 7.1428, 1.0848]}
        scale={[0.0386, 0.1301, 0.0401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Marble}
        position={[-11.8488, 7.2274, 0.9656]}
        rotation={[0.0529, -0.5352, 1.6743]}
        scale={[0.02, 0.2238, 0.0199]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[-12.0152, 7.1868, 0.8609]}
        scale={[0.0039, 0.025, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[-9.3697, 7.1428, 1.0848]}
        scale={[0.0386, 0.1301, 0.0401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-9.5526, 7.2274, 0.9656]}
        rotation={[0.0529, -0.5352, 1.6743]}
        scale={[0.02, 0.2238, 0.0199]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Darkglass}
        position={[-9.719, 7.1868, 0.8609]}
        scale={[0.0039, 0.025, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Marble}
        position={[-12.0152, 7.1868, 0.8609]}
        scale={[0.0039, 0.025, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-11.8488, 7.2274, 0.9656]}
        rotation={[0.0529, -0.5352, 1.6743]}
        scale={[0.02, 0.2238, 0.0199]}
      />
      <group
        position={[-8.9582, 9.9188, -1.8275]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[0.7493, 7.6117, 0.789]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Darkglass}
        position={[-9.8982, 7.127, 0.8366]}
        scale={[0.3856, 0.0301, 0.4007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Popart}
        position={[-9.8982, 7.0217, 0.8366]}
        scale={[0.4811, 0.1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Darkglass}
        position={[-12.1798, 7.127, 0.8366]}
        scale={[0.3856, 0.0301, 0.4007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Popart}
        position={[-12.1798, 7.0217, 0.8366]}
        scale={[0.4811, 0.1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CurveCube2.geometry}
        material={materials.Marble}
        position={[-14.9477, 5.2255, 0.4794]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.0175, 1.7607, 1]}
      />
      <group
        position={[-5.6744, 16.984, 5.6551]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.9956, 4.3303, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={nodes.Cylinder009_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={nodes.Cylinder009_2.material}
        />
      </group>
      <group
        position={[-5.6744, 16.984, 5.6551]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.9956, 4.3303, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.Darkglass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials.glow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Console_collider.geometry}
        material={nodes.Console_collider.material}
        position={[-11.02, 6.6261, 0.7964]}
        rotation={[Math.PI, -0.0073, Math.PI]}
        scale={[1.9727, 0.4207, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Console.geometry}
        material={materials.Marble}
        position={[-11.02, 6.6261, 0.7964]}
        rotation={[Math.PI, -0.0073, Math.PI]}
        scale={[1.9727, 0.4207, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.btndec001.geometry}
        material={materials.Popart}
        position={[-15.2105, 14.33, 6.4625]}
        scale={[0.4811, 0.55, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofCube2_collider.geometry}
        material={nodes.RoofCube2_collider.material}
        position={[-9.0393, 10.53, 0.3654]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.1, 7.652, 2.35]}
      />
      <group
        position={[-14.8654, 4.2016, 1.3769]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.6497, -1.0213, -0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083.geometry}
          material={nodes.Cube083.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_1.geometry}
          material={nodes.Cube083_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CurveCube2_collider.geometry}
        material={nodes.CurveCube2_collider.material}
        position={[-14.9477, 5.2255, 0.4794]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.0175, 1.7607, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall3LC_collider.geometry}
        material={nodes.Wall3LC_collider.material}
        position={[-13.2782, 4.6844, 2.7]}
        scale={[0.0912, 1.4153, 1.4029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground_collider.geometry}
        material={nodes.Ground_collider.material}
        position={[-8.9196, 0.039, -2.9461]}
        scale={[8, 0.0914, 5.6579]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window1Cube3_collider.geometry}
        material={nodes.Window1Cube3_collider.material}
        position={[-2.9301, 3.796, 3.5174]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.0962, 1.8155, 2.1544]}
      />
      <group position={[-8.0878, 2.623, 1.3399]} scale={[5.1506, 0.7467, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090.geometry}
          material={nodes.Cube090.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090_1.geometry}
          material={nodes.Cube090_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.Lacoon2}
        position={[-12.1228, 11.6543, 0]}
        rotation={[Math.PI, -0.24, Math.PI]}
        scale={[5.816, 7.7984, 5.816]}
      />
    </group>
  )
}

useGLTF.preload('/mdvr.glb')
